# Generated by Django 5.1.7 on 2025-03-14 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(unique=True)),
                ('storage_path', models.CharField(blank=True, max_length=255, verbose_name='Путь к папке пользователя в S3')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Полное имя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Биография')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('es', 'Español')], default='en', max_length=2)),
                ('timezone', models.CharField(max_length=50, verbose_name='Часовой пояс')),
                ('theme', models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('system', 'System Default')], default='light', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.role')),
            ],
            options={
                'unique_together': {('user_id', 'role')},
            },
        ),
    ]
