# Generated by Django 5.1.7 on 2025-03-14 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_role_userprofile_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='timezone',
            new_name='user_timezone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
