# Generated by Django 5.1.7 on 2025-03-15 10:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('description', models.TextField(blank=True, verbose_name='Описание команды')),
                ('owner_id', models.UUIDField(verbose_name='Владелец команды')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email приглашенного')),
                ('invited_by_id', models.UUIDField(verbose_name='Пригласивший')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник'), ('guest', 'Гость')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='teamspaces.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(verbose_name='ID пользователя')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник'), ('guest', 'Гость')], max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teamspaces.team')),
            ],
            options={
                'unique_together': {('team', 'user_id')},
            },
        ),
    ]
