# Generated by Django 5.1.7 on 2025-03-24 16:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField()),
                ('name', models.CharField(max_length=255, verbose_name='Название тимспейса')),
                ('description', models.TextField(blank=True, verbose_name='Описание тимспейса')),
                ('owner_id', models.UUIDField(null=True, verbose_name='Владелец тимспейсы')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamspaceRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeampaceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('teamspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workspaces.teamspace')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedTeamspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_by', models.UUIDField()),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(null=True)),
                ('teamspace_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='workspaces.teamspace')),
            ],
        ),
        migrations.CreateModel(
            name='TeamspaceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email приглашенного')),
                ('invited_by_id', models.UUIDField(verbose_name='Пригласивший')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник'), ('guest', 'Гость')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teamspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspaces.teamspace')),
            ],
        ),
        migrations.CreateModel(
            name='TeamspaceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_private', models.BooleanField(default=False)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('teamspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='workspaces.teamspace')),
            ],
        ),
        migrations.CreateModel(
            name='TeamspaceTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('teamspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='workspaces.teamspace')),
            ],
        ),
        migrations.CreateModel(
            name='TeamspaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(verbose_name='ID пользователя')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник'), ('guest', 'Гость')], max_length=20, verbose_name='Роль участника')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teamspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.teamspace')),
            ],
            options={
                'unique_together': {('user_id', 'teamspace')},
            },
        ),
    ]
