# Generated by Django 5.1.7 on 2025-03-14 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_remove_workspace_owner_workspace_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvite',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
